services:
    ## laravel app
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        privileged: true
        volumes:
            - ./:/var/www:Z
        ports:
            - "9000:9000"
    ## mysql 8.0
    db:
        image: mysql:8.0
        privileged: true
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_DATABASE: shopping
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
    ## nginx
    web:
        image: nginx
        restart: always
        privileged: true
        volumes:
            - ./:/var/www
            - ./storage/logs/nginx:/var/log/nginx:Z
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:Z
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:Z
        ports:
            - "80:80"
        links:
            - app
